load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@crates//:defs.bzl", "all_crate_deps")

rust_library(
    name = "alc-core-wasm",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "alc_core_wasm",
    crate_features = ["sqlx"],
    deps = all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "alc-core-wasm_test",
    crate = ":alc-core-wasm",
)
